### ISSUE TITLE
No icons on terminal

### ISSUE THREAD

**Issue by sncfsamy** [WildCodeSchool/js-poo-heracles-labour-1#3]
This workshop indicate to use icons in text, but no icons can be visible in vscode terminal or any windows terminal, only "?" in a square for all icons...
![image](https://user-images.githubusercontent.com/106074922/202405162-c7101027-3533-4df8-9b6b-e24f1ce1e85e.png)

**Comment by PPaillard** [comment]
Its because of caracter encoding.
Your terminal is maybe in UTF8 and your code in ISO 8859 (something like that)
